### PR TITLE
CMake: Include only the libraries required

### PR DESCRIPTION
**Pull request by hugueskamba**
Mbed OS now handles the dependencies.

Depends on: https://github.com/ARMmbed/mbed-os/pull/14065 and https://github.com/ARMmbed/mbed-os/pull/14079

Reviewers
@LDong-Arm @rajkan01

### CODE REVIEW

**Review by 0xc0170 — APPROVED** [review]
Looks much better now!

**Comment by 0xc0170** [comment]
Travis restarted

**Review by rajkan01 — APPROVED** [review]
LGTM

**Review by 0xc0170 — APPROVED** [review]

**Comment by 0xc0170** [comment]
Pr to master was merged, I restared travis

**Pull request merged**
