### PR TITLE
Error handling for KVStore example

### PR DESCRIPTION
**Pull request by yossi2le**
This PRs add error checkups for KVStore example.
It will print any return status with a description of expected or not expected. If the return status was not expected it will print the correct one. 
Also if the application is not supported the MBED_ERROR_UNSAPPORTED is check and the application will exit with a message.

### CODE REVIEW

**Comment by yossi2le** [comment]
@ARMmbed/mbed-os-storage  please review

**Comment by 0xc0170** [comment]
@davidsaada would this still make sense to merge?

**Comment by davidsaada** [comment]
Oh that is an oldie. Don't think it would make much sense now. But anyway, @SeppoTakalo is responsible for it now, so he should be the one to ask.

**Comment by 0xc0170** [comment]
He's not anymore. I'll close this then.

**Pull request closed without merging**
